// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TFS.API.Data
{
    public partial class LeagueMember
    {
        public LeagueMember()
        {
            LeagueMemberPlayer = new HashSet<LeagueMemberPlayer>();
        }

        public Guid Guid { get; set; }
        public Guid LeagueGuid { get; set; }
        public Guid UserGuid { get; set; }
        public string Name { get; set; }

        public virtual League LeagueGu { get; set; }
        public virtual User UserGu { get; set; }
        public virtual ICollection<LeagueMemberPlayer> LeagueMemberPlayer { get; set; }
    }
}