// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TFS.API.Data
{
    public partial class LeagueMemberPlayer
    {
        public Guid Guid { get; set; }
        public Guid LeagueMemberGuid { get; set; }
        public Guid PlayerGuid { get; set; }

        public virtual LeagueMember LeagueMemberGu { get; set; }
        public virtual Player PlayerGu { get; set; }
    }
}