// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TFS.API.Data
{
    public partial class League
    {
        public League()
        {
            LeagueMember = new HashSet<LeagueMember>();
        }

        public Guid Guid { get; set; }
        public string Type { get; set; }
        public Guid ManagerGuid { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }

        public virtual User ManagerGu { get; set; }
        public virtual ICollection<LeagueMember> LeagueMember { get; set; }
    }
}