// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TFS.API.Data
{
    public partial class PlayerGame
    {
        public Guid Guid { get; set; }
        public Guid PlayerGuid { get; set; }
        public Guid GameGuid { get; set; }
        public int Score { get; set; }

        public virtual Game GameGu { get; set; }
        public virtual Player PlayerGu { get; set; }
    }
}