// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TFS.API.Data
{
    public partial class Player
    {
        public Player()
        {
            LeagueMemberPlayer = new HashSet<LeagueMemberPlayer>();
            PlayerGame = new HashSet<PlayerGame>();
        }

        public Guid Guid { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public string Number { get; set; }
        public string Type { get; set; }

        public virtual ICollection<LeagueMemberPlayer> LeagueMemberPlayer { get; set; }
        public virtual ICollection<PlayerGame> PlayerGame { get; set; }
    }
}