// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TFS.API.Data
{
    public partial class User
    {
        public User()
        {
            League = new HashSet<League>();
            LeagueMember = new HashSet<LeagueMember>();
        }

        public Guid Guid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public virtual ICollection<League> League { get; set; }
        public virtual ICollection<LeagueMember> LeagueMember { get; set; }
    }
}