CREATE TABLE [dbo].[Player]
(
	[Guid] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] VARCHAR(511) NOT NULL,
	[Class] VARCHAR(511) NOT NULL,
	[Number] VARCHAR(511) NOT NULL,
	[Type] VARCHAR(511) NOT NULL
)
