CREATE TABLE [dbo].[User]
(
	[Guid] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[FirstName] VARCHAR(511) NOT NULL,
	[LastName] VARCHAR(511) NOT NULL,
	[Email] VARCHAR(511) NOT NULL,
	[Password] VARCHAR(511) NOT NULL
)
